name:                listzipper
version:             0.1.0.0
github:              "asada_n/listzipper"
license:             BSD3
author:              "asada_n"
maintainer:          "asada_n@worksap.co.jp"
copyright:           "2019 asada_n"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/asada_n/listzipper#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  listzipper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - listzipper

tests:
  listzipper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - listzipper
